def render_markdown(incident: dict, d: dict) -> str:
    ev = "\n".join(f"- **{e['source']}**\n  ```\n  {e['excerpt']}\n  ```" for e in d["evidence"]) or "_none_"
    steps = "\n".join(f"{i}. {s}" for i, s in enumerate(d["fix_steps"], 1)) or "_none_"
    patch = f"\n### Suggested patch\n```diff\n{d['suggested_patch']}\n```\n" if d["suggested_patch"] else ""
    return (f"## DeployDoc diagnosis: {d['summary']}\n\n"
            f"**Category:** `{d['category']}`  |  **Confidence:** {d['confidence']}%  |  "
            f"**Clouds affected:** {', '.join(d['affected_clouds']) or 'n/a'}\n\n"
            f"Run: {incident.get('run_url', '')}  (commit `{str(incident.get('sha', ''))[:7]}`)\n\n"
            f"### Root cause\n{d['root_cause']}\n\n### Evidence\n{ev}\n\n### Fix\n{steps}\n{patch}\n"
            f"### Blast radius\n{d['blast_radius'] or 'n/a'}\n\n_Generated by DeployDoc._")
